version: "3.5"

services:
  app:
    build: ./docker/app/
    image: redisforlosers/kbitb-app
    container_name: kbitb-app
    hostname: kbitb-app
    restart: always
    volumes:
      - ./src/:/var/www/html/
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db
    ports:
      - 80:80

  db:
    image: "mariadb"
    container_name: "kbitb-db"
    hostname: "kbitb-db"
    volumes:
      - "./docker/db/:/docker-entrypoint-initdb.d/"
      - "db:/var/lib/mysql/"
    environment:
      MYSQL_DATABASE: "kbitb"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "kbitb"
      MYSQL_PASSWORD: "kbitb"
    restart: "always"

  kbitb-adminer:
    image: "adminer"
    container_name: "kbitb-adminer"
    hostname: "kbitb-adminer"
    depends_on:
      - "db"
    ports:
      - "88:8080"

  kbitb-mix:
    image: "node"
    container_name: "kbitb-mix"
    hostname: "kbitb-mix"
    volumes:
      - "./src/:/app"
    working_dir: /app
    restart: always
    command: "npm run watch-poll"

volumes:
  db:
